### PR TITLE
QEA-927: Adding TestRail to Gridium

### PR DESCRIPTION
**Pull request by sethuster**
Added TestRail integration into Gridium.

### CODE REVIEW

**Review by corywest — APPROVED** [review]
LGTM

**Comment by yet-another-lucas** [comment]
Updated readme maybe? It's the part that I missed last time I added something.

**Comment by sethuster** [comment]
Updating the readme...

**Comment by yet-another-lucas** [comment]
Not gonna lie, kinda felt like a hypocrite making that comment ^_^

**Comment by sethuster** [comment]
haha no no - call me out on my bullshit.

**Pull request merged**
